### ISSUE TITLE
electron cannot be started.. 

### ISSUE THREAD

**Issue by RaynisDev** [EternalC0der/electron-nuxt3#2]
] 
[1] 07:18:38 - Found 0 errors. Watching for file changes.
[0] ✔ Nitro built in 197 ms
[0] ℹ Vite client warmed up in 659ms

**Comment by robin-schaerer** [comment]
same here

**Comment by CHH** [comment]
Hi, I've also had this issue. I have simply removed the call to "wait-on" from the --onSuccess handler. I think it's not really necessary, because Nuxt itself already waits until the page is accessible.

So my NPM script looks like this:
```
"dev:electron": "NODE_ENV=development concurrently --kill-others \"nuxt dev\" \"tsc-watch -p ./electron --outDir .output/electron --onSuccess 'electron ./.output/electron/background.js'\"",
```
